spring:
  profiles:
    group:
      "local": "common"
      "prod": "common"
---
#local
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:mysql://192.168.0.203:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rozeuS1000!
---
#prod
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:mysql://192.168.0.212:3306/test
    username: root
    password: rozeuS1000!
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config:
    activate:
      on-profile: "common"
server:
  port: 7000
  tomcat:
    uri-encoding: UTF-8

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    lazy-load-trigger-methods: true
    aggressive-lazy-loading: true
    map-underscore-to-camel-case: true
---


